Repository tvheadend/tvheadend, pull requests merged in 2024-02, with the labels that each got.

#1561 Warn missing config
  src/main.c
Labels: IMPROVEMENT, CODE

#1556 satip server: Rename nosatip to nosatipcli CLI flag
  docs/markdown/cmdline_options.md
  man/tvheadend.1
  src/main.c
Labels: CLEANUP, CODE, INTL

#1626 descrambler: Fix Sky-UK descrambling
  src/descrambler/descrambler.c
Labels: BUGFIX, CODE

#1627 dvr: Fix incorrect usage of `strerror`
  src/dvr/dvr_db.c
Labels: BUGFIX, CODE

#1606 ci: use CURL for cloudsmith.sh and enable RPM upload
  .github/workflows/build-cloudsmith.yml
  Autobuild/identify-os.sh
  support/cloudsmith.sh
Labels: IMPROVEMENT, CI

#1611 intl: update translation templates from code
  intl/docs/tvheadend.doc.pot
  intl/js/tvheadend.js.pot
  intl/tvheadend.pot
Labels: UPDATE, LOCALISATION

#1273 bouquet: Allow merging of services across network bouquet, fixes #5617
  src/bouquet.c
Labels: FEATURE, CODE

#1644 ci: Enforce rebasing PRs before merging
  .github/workflows/block-merge-commits.yml
  .github/workflows/enforce-pr-rebase.yml
Labels: CI

#1646 Replace single-bit signed integers with unsigned integers
  src/http.h
Labels: IMPROVEMENT, CODE

#1647 Add missing htmsg_destroy() call in hdhomerun_server_discover
  src/webui/webui.c
Labels: BUGFIX, CODE

#1623 Add support for 12-hour custom date formats
  src/webui/static/app/tvheadend.js
Labels: IMPROVEMENT, CODE

#1648 Add some ERRNOs for DVR
  src/config.c
  src/dvr/dvr_rec.c
  src/dvr/dvr_vfsmgr.c
Labels: IMPROVEMENT, CODE

#1645 Replace poison memset by memset_s to avoid compiler optimizing it out
  src/input/mpegts/mpegts_table.c
  src/tvheadend.h
Labels: IMPROVEMENT, CODE

#1657 ci: change CLOUDSMITH_OWNER from a var to a secret
  .github/workflows/build-cloudsmith.yml
Labels: CI
