Repository tvheadend/tvheadend, pull requests merged in 2025-05, with the labels that each got.

#1786 lovcombo-all.js: Fix autorec create/edit TypeError with Firefox 134
  src/webui/static/lovcombo/lovcombo-all.js
Labels: READY-FOR-MERGE

#1813 httpc.c: Fix HTTPS with OpenSSL 3.5
  src/httpc.c
Labels: BUGFIX, CODE, READY-FOR-MERGE

#1793 Remove links to old Wiki
  CONTRIBUTING.md
  LICENSE.md
  README.md
  docs/markdown/doc_about.md
  docs/markdown/doc_update.md
  docs/markdown/firstconfig.md
  docs/markdown/installation.md
  docs/markdown/introduction.md
  src/webui/static/app/tvheadend.js
  support/changelog
Labels: DOCUMENTATION, CLEANUP, READY-FOR-MERGE

#1802 Global setting for 'Items per page'
  docs/property/page_size.md
  src/access.c
  src/access.h
  src/config.c
  src/config.h
  src/webui/comet.c
  src/webui/static/app/config.js
  src/webui/static/app/idnode.js
  src/webui/static/app/tvheadend.js
Labels: IMPROVEMENT, CODE, READY-FOR-MERGE

#1810 Fix crash when updating 'disp_summary'
  src/dvr/dvr_db.c
Labels: BUGFIX, CODE, READY-FOR-MERGE

#1821 Fix GCC 15+ format-truncation compile error by enlarging EPG language buffer
  src/wizard.c
Labels: IMPROVEMENT, CODE

#1801 Show recording file name on DVR info page
  src/webui/static/app/dvr.js
  src/webui/static/app/idnode.js
Labels: IMPROVEMENT, CODE, READY-FOR-MERGE

#1800 allow NVENC, VAAPI and MMAL to coexist in the same build
  src/transcoding/codec.h
  src/transcoding/codec/internals.h
  src/transcoding/codec/profile.c
  src/transcoding/codec/profile_video_class.c
  src/transcoding/transcode/stream.c
  src/webui/static/app/codec.js
Labels: IMPROVEMENT, CODE, READY-FOR-MERGE

#1807 fix read/write of PT_DYN_INT
  src/prop.c
Labels: BUGFIX, CODE

#1748 iptv: handle relative key URL
  src/input/mpegts/iptv/iptv_http.c
Labels: NEEDS-MORE-INFO

#1792 update vaapi transcoding as recommended by ffmpeg 6.1.1/doc/examples/…
  src/libav.h
  src/transcoding/transcode/hwaccels/hwaccels.c
  src/transcoding/transcode/hwaccels/hwaccels.h
  src/transcoding/transcode/hwaccels/vaapi.c
  src/transcoding/transcode/hwaccels/vaapi.h
  src/transcoding/transcode/video.c
Labels: IMPROVEMENT, CODE

#1814 add mpegts parameters from input stream
  src/muxer.h
  src/muxer/muxer_libav.c
  src/profile.c
  src/transcoding/transcode/transcoder.c
  src/webui/static/app/profile.js
Labels: IMPROVEMENT, READY-FOR-MERGE
